backend:
  name: git-gateway
  branch: master

media_folder: static/assets/uploads
public_folder: /assets/uploads

collections:
  - name: "general"
    label: "General"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "about"
        file: "src/content/general.md"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "general"}
          - {label: "Title", name: "title", widget: "string", required: true}
